version: '3'

services:
  hhh-db:
    image: postgres:15
    container_name: hhh_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5433"
    ports:
      - "15432:5433"
    volumes:
      - ./docker/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    command: -p 5433
      
  hhh-backend:
    image: hhh-backend:0.0.1
    build: ./hhh-backend
    container_name: hhh_backend
    ports:
      - "8081:8081"
    depends_on:
      - hhh-db
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hhh-db:5433/hhh
      
volumes:
  db-data: